# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ezvGYDuBg-J9k_-qAxjB0vCpOJnyqgPn
"""

import numpy as np

print("----- CREATE MULTIDIMENSIONAL ARRAY -----")

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr)

print("\n----- ACCESS VALUES USING INDEX -----")

print("First Element:", arr[0][0])
print("Middle Element:", arr[1][1])
print("Last Element:", arr[2][2])

print("\n----- MATHEMATICAL OPERATIONS -----")

print("Addition:")
print(arr + 10)

print("\nSubtraction:")
print(arr - 5)

print("\nMultiplication:")
print(arr * 2)

print("\nDivision:")
print(arr / 2)

print("\n----- NUMPY METHODS -----")

# 1
print("Shape:", arr.shape)

# 2
print("Size:", arr.size)

# 3
print("Dimensions:", arr.ndim)

# 4
print("Data Type:", arr.dtype)

# 5
print("Maximum:", np.max(arr))

# 6
print("Minimum:", np.min(arr))

# 7
print("Sum:", np.sum(arr))

# 8
print("Mean:", np.mean(arr))

# 9
print("Median:", np.median(arr))

# 10
print("Standard Deviation:", np.std(arr))

# 11
print("Transpose:")
print(arr.T)

# 12
print("Flatten:")
print(arr.flatten())

# 13
print("Square Root:")
print(np.sqrt(arr))

# 14
print("Power of 2:")
print(np.power(arr, 2))

# 15
print("Sorted Array:")
print(np.sort(arr))

# 16
print("Reshape to 1x9:")
print(arr.reshape(1, 9))

# 17
print("Unique Values:")
print(np.unique(arr))